apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:6lZM4m2XSZixGi6gdkj3zp7RJFb6sWhm9w==,iv:DQBQ6Bi65P5msCR5wzgWf9kE4kDp2alzZcqbFz1N3uc=,tag:glio8C0NR8ZCKAEsFxYTzA==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4YmZupsG1bTqk792QulKTdZww2IO0fITj10wT2sCUQ==,iv:ebc0K42dh2IYL1xGQcIOTgisAcak4Inj3e9/7wkaEnE=,tag:jhHV6yTfK6E1fO03MLU6qQ==,type:str]
sops:
  age:
    - recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK2x1YmdqZjBSWmc5Vnc2
        VlJPOGxJbFRkN0lNcEoxOE4zb2VuOVRYYmtJCkp0b1ZhbU1jaFVjS3NKMjRrNVls
        WVdSeXl2NnExSWZkNTV4dkd1MHB6VjgKLS0tIFg5VEkzNXJVclZnUFlna05tVmt1
        UXJyaGJKK1FCK01zbzhUWVV1cjcvaUkKtQnB5P1rOeaUiAQNdvW9BdBJgY+BKE45
        o4YUR2NvB1uO0yPVwOPbLXBvjHEhosJh0HT7KKbbiT1Zm63akZ/VDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T13:47:44Z"
  mac: ENC[AES256_GCM,data:QDomWl+N2btMkT4VJCweRuZJgeoDIZ2mvNzRbaxQ1Mez4hIZL85ak64rJWwMzDmDhIiOCgYftO9pIafu376pY16wP4GE3nCva5NuSLk46whXGV7jTND8Z7Ho7iKndqAdFw5uvjXzlj6AlswQgQwUBQzQtEg7sHhbTYWTPgn3Nh0=,iv:568m1Vd3i/L5cwdeLM48ZCa2iLzbe6g0cPNbQgx6Fdg=,tag:dUPH3lbx4hjG08+363D6gw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
