---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
components:
  - ../../components/common
resources:
  - ./namespace.yaml # Needs creation before the DB/PVC which aren't helm releases
  - ./immich/ks.yaml
  - ./postgres/ks.yaml
