apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 3

  storage:
    size: 1Gi
    storageClass: local-path

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      dataChecksums: true
      # TODO: Use managed extensions (pg 18)
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;

  backup:
    barmanObjectStore:
      destinationPath: "s3://scottgorlin-k8s-backup/cnpg"
      endpointURL: "https://s3.us-west-000.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: backblaze-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backblaze-credentials
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-database-backup
spec:
  cluster:
    name: immich-database
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
