---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
spec:
  interval: 1h
  chart:
    spec:
      chart: gitea
      version: 12.5.0
      sourceRef:
        kind: HelmRepository
        name: gitea
  values:
    strategy:
      type: Recreate # RollingUpdate causes locks on pods using RWO volumes
      clusterDomain: "${SECRET_DOMAIN}"
    valkey-cluster:
      enabled: true
      persistence:
        enabled: true
        storageClass: local-path
    valkey:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false

    persistence:
      enabled: true

    gitea:
      oauth:
        - name: "authentik"
          provider: "openidConnect"
          existingSecret: gitea-authentik-secret
          autoDiscoverUrl: "https://authentik.${SECRET_DOMAIN}/application/o/gitea/.well-known/openid-configuration"
          iconUrl: "https://authentik.${SECRET_DOMAIN}/static/dist/assets/icons/icon.png"
          scopes: "email profile"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      config:
        server:
          DOMAIN: "git.${SECRET_DOMAIN}"
          ROOT_URL: "https://git.${SECRET_DOMAIN}/"
          SSH_DOMAIN: "git.${SECRET_DOMAIN}"
        database:
          DB_TYPE: postgres
#          HOST: "${host}"
#          NAME: "${dbname}"
#          USER: "${user}"
#          PASSWD: "${password}"
#          SCHEMA: "${dbname}"

      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__HOST
          valueFrom:
            secretKeyRef:
              name: gitea-postgres-app
              key: host
        - name: GITEA__DATABASE__NAME
          valueFrom:
            secretKeyRef:
              name: gitea-postgres-app
              key: dbname
        - name: GITEA__DATABASE__USER
          valueFrom:
            secretKeyRef:
              name: gitea-postgres-app
              key: user
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-postgres-app
              key: password
        - name: GITEA__DATABASE__SCHEMA
          value: public
#          valueFrom:
#            secretKeyRef:
#              name: gitea-postgres-app
#              key: dbname
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitea
  namespace: &namespace gitea
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
      namespace: kube-system
      sectionName: https
  hostnames:
    - "git.${SECRET_DOMAIN}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gitea-http
          namespace: *namespace
          port: 3000
