---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./multus-daemonset-thick.yml
  - ./storage-nad.yaml
  - ./k8s-nad.yaml

patches:
  - path: ./patches/volume-mount.yaml
  - path: ./patches/oom.yaml
  - path: ./patches/missing-binaries.yaml
