---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./multus-daemonset-thick.yml
#  - ./dhcp-daemonset.yml  # wget https://raw.githubusercontent.com/k8snetworkplumbingwg/reference-deployment/refs/heads/master/multus-dhcp/dhcp-daemonset.yml
  - ./storage-nad.yaml
  - ./k8s-nad.yaml
  - ./whereabouts.yaml # helm template whereabouts oci://ghcr.io/k8snetworkplumbingwg/whereabouts-chart > whereabouts.yaml

patches:
  - path: ./patches/volume-mount.yaml
#  - path: ./patches/volume-mount-dhcp.yaml
  - path: ./patches/oom.yaml
  - path: ./patches/missing-binaries.yaml
