---
# Source: whereabouts-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whereabouts-whereabouts-chart
  namespace: kube-system
  labels:
    helm.sh/chart: whereabouts-chart-0.9.2
    app: whereabouts-chart
    app.kubernetes.io/name: whereabouts-chart
    app.kubernetes.io/instance: whereabouts
    app.kubernetes.io/version: "v0.9.2"
    app.kubernetes.io/managed-by: Helm
---
# Source: whereabouts-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: whereabouts-whereabouts-chart-config
  namespace: kube-system
  annotations:
    kubernetes.io/description: |
      Configmap containing user customizable cronjob schedule
data:
  cron-expression: "30 4 * * *" # Default schedule is once per day at 4:30am. Users may configure this value to their liking.
---
# Source: whereabouts-chart/templates/cluster_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whereabouts-whereabouts-chart
rules:
- apiGroups:
  - whereabouts.cni.cncf.io
  resources:
  - ippools
  - overlappingrangeipreservations
  - nodeslicepools
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups: ["k8s.cni.cncf.io"]
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
    - events
  verbs:
  - create
  - patch
  - update
  - get
---
# Source: whereabouts-chart/templates/cluster_role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: whereabouts-whereabouts-chart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: whereabouts-whereabouts-chart
subjects:
- kind: ServiceAccount
  name: whereabouts-whereabouts-chart
  namespace: kube-system
---
# Source: whereabouts-chart/templates/daemonset.yaml
# Dont'forget to update doc/crds/daemonset-install.yaml as well
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whereabouts-whereabouts-chart
  namespace: kube-system
  labels:
    helm.sh/chart: whereabouts-chart-0.9.2
    app: whereabouts-chart
    app.kubernetes.io/name: whereabouts-chart
    app.kubernetes.io/instance: whereabouts
    app.kubernetes.io/version: "v0.9.2"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      name: whereabouts
      app: whereabouts-chart
      app.kubernetes.io/name: whereabouts-chart
      app.kubernetes.io/instance: whereabouts
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: whereabouts
        app: whereabouts-chart
        app.kubernetes.io/name: whereabouts-chart
        app.kubernetes.io/instance: whereabouts
    spec:
      hostNetwork: true
      serviceAccountName: whereabouts-whereabouts-chart
      securityContext:
        {}
      containers:
        - name: whereabouts-chart
          securityContext:
            privileged: true
          image: "ghcr.io/k8snetworkplumbingwg/whereabouts:v0.9.2"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args:
            - -c
            - |
              SLEEP=false source /install-cni.sh
              /token-watcher.sh &
              /ip-control-loop -log-level debug
          env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: WHEREABOUTS_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
          - name: cnibin
            mountPath: /host/opt/cni/bin
          - name: cni-net-dir
            mountPath: /host/etc/cni/net.d
          - name: cron-scheduler-configmap
            mountPath: /cron-schedule
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        - name: cron-scheduler-configmap
          configMap:
            name: whereabouts-whereabouts-chart-config
            defaultMode: 0744
            items:
            - key: "cron-expression"
              path: "config"
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
---
# Source: whereabouts-chart/templates/node-slice-controller.yaml
# Dont'forget to update doc/crds/node-slice-controller.yaml as well
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereabouts-whereabouts-chart-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereabouts-whereabouts-chart-controller
  template:
    metadata:
      labels:
        app: whereabouts-whereabouts-chart-controller
    spec:
      containers:
        - command:
            - /node-slice-controller
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: WHEREABOUTS_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: "ghcr.io/k8snetworkplumbingwg/whereabouts:v0.9.2"
          name: whereabouts
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cnibin
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /cron-schedule
              name: cron-scheduler-configmap
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-6kd6k
              readOnly: true
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: whereabouts-whereabouts-chart
      serviceAccountName: whereabouts-whereabouts-chart
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /opt/cni/bin
            type: ""
          name: cnibin
        - hostPath:
            path: /etc/cni/net.d
            type: ""
          name: cni-net-dir
        - configMap:
            defaultMode: 484
            items:
              - key: cron-expression
                path: config
            name: whereabouts-whereabouts-chart-config
          name: cron-scheduler-configmap
        - name: kube-api-access-6kd6k
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
