apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-postgres
spec:
  instances: 3

  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      localeCollate: 'en_US.UTF-8'
      localeCType: 'en_US.UTF-8'
      dataChecksums: true

  storage:
    size: 1Gi
    storageClass: local-path

  backup:
    barmanObjectStore:
      destinationPath: "s3://scottgorlin-k8s-backup/cnpg"
      endpointURL: "https://s3.us-west-000.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: backblaze-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backblaze-credentials
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: gitea-postgres-backup
spec:
  cluster:
    name: gitea-postgres
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
