apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-postgres
spec:
  instances: 3

  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      localeCollate: 'en_US.UTF-8'
      localeCType: 'en_US.UTF-8'
      dataChecksums: true

  storage:
    size: 1Gi
    storageClass: local-path
