---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: "https://flux-webhook.${SECRET_DOMAIN}"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"

metrics: true

ui:
  title: Status | Gatus
  header: Status
  # https://docs.gravatar.com/sdk/images/
  logo: https://gravatar.com/avatar/ddd4bcc0c18b8b2ee60a05022383f235b78ac3fb886db13430f3830233ad91d9
  link: https://github.com/gorlins
  buttons:
    - name: Github
      link: https://github.com/gorlins

    - name: Homelab
      link: https://github.com/gorlins/home_ops

web:
  port: ${GATUS_WEB_PORT}
