# Docker Compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8010.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Open portainer Stacks list and click 'Add stack'
# - Paste the contents of this file and assign a name, e.g. 'paperless'
# - Upload 'docker-compose.env' by clicking on 'Load variables from .env file'
# - Modify the environment variables as needed
# - Click 'Deploy the stack' and wait for it to be deployed
#
# For more extensive installation and update instructions, refer to the
# documentation.
services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - backend
  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - backend
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
#    ports:
#      - "8010:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paperless.soybagel.com`)"
      - "traefik.http.routers.paperless.entrypoints=websecure"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      - "traefik.http.routers.paperless.service=paperless"
      - "traefik.http.routers.paperless.tls.certresolver=leresolver"
    networks:
      - backend
      - public
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
#      - ./export:/usr/src/paperless/export
      - omv_export:/usr/src/paperless/export
#      - ./consume:/usr/src/paperless/consume
      - omv_consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_URL: https://paperless.soybagel.com
      PAPERLESS_DBHOST: db
      PAPERLESS_SECRET_KEY:
      PAPERLESS_TIME_ZONE: America/New_York
      NAS_USER:
      NAS_PASSWORD:
volumes:
  data:
  media:
  pgdata:
  redisdata:
  omv_export:
    driver: local
    driver_opts:
      type: "cifs"
      device: "//omv.soybagel.com/paperless_export"
      o: "addr=omv.soybagel.com,username=${NAS_USER},password=${NAS_PASSWORD},vers=3.0,uid=1000,gid=100"
  omv_consume:
    driver: local
    driver_opts:
      type: "cifs"
      device: "//omv.soybagel.com/paperless_consume"
      o: "addr=omv.soybagel.com,username=${NAS_USER},password=${NAS_PASSWORD},vers=3.0,uid=1000,gid=100"

networks:
  public:
    external: true
  backend:
