# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.8.8.8:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.8.8.8"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-pi"
    ipAddress: "10.8.8.18"
    installDisk: "/dev/mmcblk0"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ee21ef4a5ef808a9b7484cc0dda0f25075021691c8c09a276591eedb638ea1f9
    controlPlane: true
    networkInterfaces:
      - interface: end0
        dhcp: true
        vip:
          ip: "10.8.8.8"
  - hostname: "talos-2"
    ipAddress: "10.8.8.127"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b56a539b12ecc6c822bb4cc7d53eae1db898799815705aa278dab74f38404b47
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: "10.8.8.8"
  - hostname: "talos-3"
    ipAddress: "10.8.8.123"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b56a539b12ecc6c822bb4cc7d53eae1db898799815705aa278dab74f38404b47
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: "10.8.8.8"
  - hostname: "talos-w1"
    ipAddress: "10.8.8.118"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b56a539b12ecc6c822bb4cc7d53eae1db898799815705aa278dab74f38404b47
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:cc:3f:12"
        dhcp: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:6a:00:a5"
        dhcp: false
        mtu: 9000
  - hostname: "talos-w2"
    ipAddress: "10.8.8.119"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b56a539b12ecc6c822bb4cc7d53eae1db898799815705aa278dab74f38404b47
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:3a:43:88"
        dhcp: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:c3:46:2a"
        dhcp: false
        mtu: 9000
  - hostname: "talos-w3"
    ipAddress: "10.8.8.112"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b56a539b12ecc6c822bb4cc7d53eae1db898799815705aa278dab74f38404b47
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:aa:d4:ce"
        dhcp: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:bd:11:9a"
        dhcp: false
        mtu: 9000

# Global patches
patches:
  - "@./patches/global/cluster.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-kernel.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

# Worker patches
worker:
  userVolumes:
    - name: data
      provisioning:
        diskSelector:
          match: "!system_disk"
        minSize: 50GB
        grow: true
  patches:
    - "@./patches/worker/machine-kubelet.yaml"
