apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  storageClassName: longhorn # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce # Access mode requested (e.g., ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  resources:
    requests:
      storage: 100Gi # Amount of storage requested (e.g., 500Mi, 10Gi)
