---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
  namespace: &namespace longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.10.*
      sourceRef:
        kind: HelmRepository
        name: *app
  values:
    defaultSettings:
      # Set this so that we can use the Talos UserVolume
      defaultDataPath: /var/mnt/data/longhorn

    persistence:
      defaultDataLocality: best-effort

    httproute:
      enabled: true
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: internal
          namespace: kube-system
          sectionName: https
      hostnames:
        - "longhorn.${SECRET_DOMAIN}"

    metrics:
      serviceMonitor:
        enabled: true
