---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
  namespace: &namespace longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.10.*
      sourceRef:
        kind: HelmRepository
        name: *app
  values:
    defaultSettings:
      # Set this so that we can use the Talos UserVolume
      defaultDataPath: /var/mnt/data/longhorn
      defaultDataLocality: best-effort

    persistence:
      defaultDataLocality: best-effort

# not available yet in 1.10.1
#    httproute:
#      enabled: true
#      parentRefs:
#        - group: gateway.networking.k8s.io
#          kind: Gateway
#          name: internal
#          namespace: kube-system
#          sectionName: https
#      hostnames:
#        - "longhorn.${SECRET_DOMAIN}"

    metrics:
      serviceMonitor:
        enabled: true

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-httproute
  labels:
    app: longhorn-httproute
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      name: internal
      namespace: kube-system
      sectionName: https
  hostnames:
    - "longhorn.${SECRET_DOMAIN}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: longhorn-frontend
      port: 80
