apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  bootstrap:
    initdb:
      dataChecksums: true

  storage:
    size: 1Gi
    storageClass: local-path

  backup:
    barmanObjectStore:
      destinationPath: "s3://scottgorlin-k8s-backup/cnpg"
      endpointURL: "https://s3.us-west-000.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: backblaze-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backblaze-credentials
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-example-backup
spec:
  cluster:
    name: cluster-example
  schedule: '0 0 0 * * *'
  backupOwnerReference: self

# Plugin method is preferred way forward, but not working yet
#  plugins:
#    - name: barman-cloud.cloudnative-pg.io
#      isWALArchiver: true
#      parameters:
#        barmanObjectName: backblaze
#
#---
#apiVersion: barmancloud.cnpg.io/v1
#kind: ObjectStore
#metadata:
#  name: backblaze
#spec:
#  configuration:
#    destinationPath: "s3://scottgorlin-k8s-backup/cnpg"
#    endpointURL: "https://s3.us-west-000.backblazeb2.com"
#    s3Credentials:
#      accessKeyId:
#        name: backblaze-credentials
#        key: ACCESS_KEY_ID
#      secretAccessKey:
#        name: backblaze-credentials
#        key: ACCESS_SECRET_KEY
#  instanceSidecarConfiguration:
#    env:
#      - name: AWS_REQUEST_CHECKSUM_CALCULATION
#        value: when_required
#      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
#        value: when_required

