apiVersion: v1
kind: Secret
metadata:
  name: headlamp-authentik
type: Opaque
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:/X6o7XeJkh6FXfPmhXECFzruh8cVFX3+vFGJ2R7bxI3wIxO43sRsaw==,iv:Zlj8v1/MEkDX+qYL5s0Zak2dWzZAgADhL8fS/adOsdg=,tag:dWZrywIL6pE5WHSg3kAJRA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ghhiauGKrfxDpjlKNQRuhTyu3rcubaCKIOCPv0DaGrjf/b2wfzLftYK6JEbrqZLsQTTVavckPa1mhCzjFB4AqivUAhy4ozbL+m/8SkYiftONOXiWEU2lbT2uCT9Vc6m7oIb63Nda+aKqyXktZr+YeMOwMLwFJnDZX1ewmnouADE=,iv:aSHtCD6tqSxkuofW9OC3dyxh+sE3jj/TMpU61b57qpc=,tag:48uSnqvPRmpkSND8iq1cHA==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:3AcXQby3/j1j0dKQh713Aaz8+LEn8lNQDIpCX/bAWvCZNRM0ru5vwX/ctNQOq67IHnfjlqeg,iv:NJhS6KFO7V7JuDL+ni/VuzagJttCp7pg0jMgU5nVNqU=,tag:8zIwj9y7x3cZlIgfIhW6Xw==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:RfaFP1GZn5vBrvGZqZZUznVMo1M=,iv:/kcX/ElEjkErpxBAyNyqJGxh3S8u8ALYunbO/Fnr7Ec=,tag:pa4BOVzr1BGDK+81qOeHfw==,type:str]
sops:
  age:
    - recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZLy9WY3o5QkpzRlRtVjVM
        MzBuc0N2UjBQQm01SFRRYXl5UHdVQjRKN0IwClkwZkVpT3lDeERNZU11eEJjKzJV
        V2h2OTJHNDEydkI4eUxTWitwdmpYd1EKLS0tIFVUOTY2VS9lanA4di9LQVRMUVdZ
        Ny85bUdwYXhuRWZoQTNWZ3FsU2pLQUEKz6vl17RkDree8Ub2xBdw6uB0GH7kXRA+
        EH0LJ3C1AXqwkUnPEx/X4Z11DNS1XP0+TaPjvpEwN7sqiXYkFOi6oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T18:57:05Z"
  mac: ENC[AES256_GCM,data:Y/XHy+Xlb1XXogIoNfsBVE8sY7goFTZrpbJflSJMmHC3g/8SZr++h8DiJyM6+r2lZ0gnUY5NZTwGvBCR0ofqkBue3oDoXDdz+ZDsy2oTBh2Yd96fTWwAlLbDQkhRC5GMwYYH/1hFVnH0HVLfg+VxVzftMiifqCBd5hsPP4LMxCU=,iv:SjMBmizA+cYecDgzj2uiObTOL+F0UJQ15bxO0XtJ6kU=,tag:gGebLjjy23cl00SUxhE/cQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
