---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-storage
  namespace: local-path-storage
spec:
  interval: 1h
  chart:
    spec:
      chart: ./local-path-provisioner/deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-storage
  values:
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths: []
      - node: talos-w1
        paths:
          - /var/mnt/data/local-path-storage
      - node: talos-w2
        paths:
          - /var/mnt/data/local-path-storage
      - node: talos-w3
        paths:
          - /var/mnt/data/local-path-storage

